.TH SystemChecker 1 "14 October 2019" "version 1.0"
.SH NAME
SystemChecker. A simple tool to check various system specs
.SH SYNOPSIS
Usage : ./state.sh [-h | --help] [-u | --user] [-s | --system] [-r | --resources] [-b | --boot]
.PP
.B -h | --help
\tPrint the help and quit the program
.PP
.B -u | --user
\tPrint the current connected user
.PP
.B -s | --system
\tPrint all the system information
.PP
.B -r | --resources
\tPrint the resources usage
.PP
.B -b | --boot
\tPrint if critical boot errors were found
.SH EXAMPLES
.B ./state.sh -h\t
Print the help
.PP
.B ./state.sh -u --system\t
Print the user information, as well as system information
.PP
.B ./state.sh -rs --user\t
Print the resources usage, then the user info, and finally the system info
.SH SEE ALSO
.B uname
.PP
.B who
.PP
.B journalctl
.PP
.B free
.SH BUGS
The program doesn't display any colors if the OS is BSD-Based.
.SH AUTHOR
Pablo Bondia-Luttiau, Daël Mombo-Mombo
.SH COPYRIGHT
Copyright © 2019 Free Software Foundation, Inc.  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
       This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
