.TH Daemon 1 "14 October 2019" "version 1.0"
.SH NAME
Daemon. A tool to automate wallpaper changing
.SH SYNOPSIS
Usage : ./install.sh
.PP
.SH EXAMPLES
.B ./install.sh
Install the corresponding daemon and start it
.PP
.SH SEE ALSO
.B systemctl
.SH BUGS
The daemon does not restart itself after reboot. This is a WIP
.PP
.SH AUTHOR
Pablo Bondia-Luttiau, Daël Mombo-Mombo
.SH COPYRIGHT
Copyright © 2019 Free Software Foundation, Inc.  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
       This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
